site_name: Funky Penguin's Geek's Cookbook
site_description: 'A short description of my project'
site_author: 'David Young'
site_url: 'https://geeks-cookbook.funkypenguin.co.nz'
edit_uri: 'edit/master/manuscript/'

# Repository
repo_name: 'funkypenguin/geek-cookbook'
repo_url: 'https://github.com/funkypenguin/geek-cookbook'

# Set this to "manuscript" so that we can produce leanpub content
docs_dir: 'manuscript'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 David Young'


theme: material
theme_dir: mkdocs-material
pages:
    - Home : index.md
    - Introduction:
      - README: README.md
      - whoami: whoami.md
    - Essential:
      - Design: ha-docker-swarm/design.md
      - VMs: ha-docker-swarm/vms.md
      - Shared Storage (Ceph): ha-docker-swarm/shared-storage-ceph.md
      - Shared Storage (GlusterFS): ha-docker-swarm/shared-storage-gluster.md
      - Keepalived: ha-docker-swarm/keepalived.md
      - Traefik: ha-docker-swarm/traefik.md
      - Docker Swarm Mode: ha-docker-swarm/docker-swarm-mode.md
    - Recommended:
      - Mail Server: recipies/mail.md
      - GitLab: recipies/gitlab.md
      - GitLab Runner: recipies/gitlab-runner.md
      - Wekan: recipies/wekan.md
      - Piwik: recipies/piwik.md
      - Tiny Tiny RSS: recipies/tiny-tiny-rss.md
    - Reference:
      - OAuth Proxy: reference/oauth_proxy.md
      - Networks: reference/networks.md
#      - Basic: advanced/tiny-tiny-rss.md
#      - Plugins: advanced/tiny-tiny-rss.md
#      - Themes: advanced/tiny-tiny-rss.md

#        - Home Assistant:
#          - About: advanced/home-assistant/basic.md
#          - Basic: advanced/home-assistant/basic.md
#          - Grafana: advanced/home-assistant/grafana.md
#          - Limitless LED: advanced/home-assistant/limitless-led.md
#          - OwnTracks: advanced/home-assistant/limitless-led.md

#        - Home Assistant:

#          - About: advanced/home-assistant/basic.md
#          - Basic: advanced/home-assistant/basic.md
#          - Grafana: advanced/home-assistant/grafana.md
#          - Limitless LED: advanced/home-assistant/limitless-led.md
#          - OwnTracks: advanced/home-assistant/limitless-led.md

#        - Huginn: advanced/huginn.md
#        - Nextcloud: advanced/nextcloud.md
#        - OwnTracks: advanced/owntracks.md
#        - Shaarli: advanced/shaarli.md
#        - Wallabag: advanced/wallabag.md




extra:
  disqus: 'geeks-cookbook'
  logo: 'images/site-logo.png'
  feature:
    tabs: false
  palette:
    primary: 'brown'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/funkypenguin'
    - type: 'twitter'
      link: 'https://twitter.com/funkypenguin'
    - type: 'stack-overflow'
      link: 'https://stackoverflow.com/cv/funkypenguin'
    - type: 'rss'
      link: 'https://www.funkypenguin.co.nz/blog/'
    - type: 'envelope'
      link: 'mailto:davidy@funkypenguin.co.nz?Subject=Hello%2C%20from%20a%20geek-cookbook%20reader%20%3B%29'
    - type: 'book'
      link: 'https://leanpub.com/geeks-cookbook'

# Google Analytics
google_analytics:
  - 'UA-139253-18'
  - 'auto'

extra_javascript:
  - 'extras/javascript/piwik.js'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
